travis:
  secure:
    BINSTAR_TOKEN: npqfF7gOsttI28VTBtDntd8gPwzwCPWuVO19EZcodJOEWPLupYgwJpTP5ba4qZEdKyNBk+pDnUKQS40mzSVgvanCyCCf6Kiw+2G9l8IiEZ0oOWBcQ5lPQO+igNM6HJveuTQsx9+z2+REB/TZ06+HLW1Xpmva/tguF+tce0evLnpPP979BaPZZrwwHHPlj60Qjcq9LWtQgLqFL4qcruhw0w7MGNEVQ02j6mAdkrRhDsVJ7JDIa6qWJcO48+hxdopIlE4gvUwuq9Qdo6n2Ja9zPiS6x22HRNYsshyjEq3X18I1337Ik/v3EmzB3xfC7LotO/ykXBRMhHc3O+5Acj7k/wxQ9wqfFyhYweF/EPO5MbKvpq13IdXGGmmXD6APBdf82hM6CK/oBAhBD91ysPemA7ja5NZjOR0Tx6ndB8RKKuqFtlKcwxp7rtB3qYSLDHpEJdP/EkKnNBbBDx5bhluIBUbCvGguSBZLU9V3IAeDcRanSnthTWo73Lh+W1F0jNvYnfkSMIk5PPxmgNMf9uwTzY01Cni9Bqngy/+mi3soljkikeqIdzF85fpL02hwqYj66M2/MJgdzJuczSD/h6JyO6sDFTTjCV/Y23C01jx0kKkeABDwxsIMlIYyg5eqwjNjEXsVQGADtjNUiX/ro37i5WkN/xProyVTgSNk2tvbVV0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
