travis:
  secure:
    BINSTAR_TOKEN: vTsL2C8sympqD179iwhcfmWYyf9thirx4DFr9grNyDuGGLZedQp/MjMa90Ee5VQB7yOapsTVe+AxtnTWBanUt9ycXNb8H5E25FMkRLK7pcnoJFnTcAIpPvzhyGQ2eIZV2wMJknUR//cD1pqS9do/xfyibvHPvEWAjMaZYSBsVnoNdIQEAswCi49hkpYxqA5fO2Xfwdp8ve2SlZgn72vCvf2VRYq8AL3oCMVVTqX/17733fRUDn1U9iEikdx554QKI0jqak0ZJD4/4YN0rT+INRty5Loi8TiyLobBQj4EKNQoDEklFd8ZfkzlX8XtqwKqiHKyjPMm5bZDvkop7MyA6yttlFZjOSSoydL4ZCiYsiV4Tu91XHuN/oYUEWZ1K0qlygzeXZmnWbuHwUwqt7SSwMEBFVtWgLZqCQIKjCnQKmZAqYj13E89fuFV2Sruhdr7KHeAKGYhg4rmHF59UhsSwlT1Ct/1YDVWxbIVOdL0eMCxRhLGBrfbswQKswHrREHbwbRj3vXXri67s3EQ8v4hKlSDMxaq7fHlURnTxR5HqWvXE1zJo8uloaX9oqLQ1f3yU8+lwHdb+qSGhj648TgkqUmKRpEW6x9sUa2oIqmFgYgmhtaSnHqVIvwl/w4aOzrfZG5ubgftjnx5l3e8A8lMrjuq7irgjdgcva3xjFzRtwY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
